<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<div class="ui uit type1 mb_30"> 
<div class="inner"> <span class="tp_icon circle circle1"> <span class="tp_icon icon icon3"></span> </span> 
<div class="txtwrap"> <strong class="tit_inner">지구단위계획 정의</strong> 
<p class="txtp">도시계획 수립 대상지역 안의 일부에 대하여 토지이용을 합리화 하고 그 기능을 증진시키며, 미관 개선 및 양호한 환경확보와 해당 지역을 체계적&middot;계획적으로 관리하기 위하여 수립하는 도시관리 계획</p> </div> </div> </div> 
<h2>근거법률</h2> 
<p class="txtp">『국토의 계획 및 이용에 관한 법률』,『당진시 도시계획조례』</p> 
<h2>지구단위계획 정의</h2> 
<p class="txtp">도시계획 수립 대상지역 안의 일부에 대하여 토지이용을 합리화 하고 그 기능을 증진시키며, 미관 개선 및 양호한 환경확보와 해당 지역을 체계적&middot;계획적으로 관리하기 위하여 수립하는 도시관리 계획</p> 
<h2>지구단위계획 내용</h2> 
<ul class="list_1st"> 
<li>용도지역&middot;용도지구의 세분 또는 변경에 관한 사항</li> 
<li>기반시설(도로&middot;공원&middot;학교&middot;주차장&middot;공공공지 등)의 배치와 규모에 관한 사항</li> 
<li>토지의 규모와 조성계획에 관한 사항</li> 
<li>건축물의 용도, 건폐율, 용적률, 높이 등에 관한 계획</li> 
<li>건축물의 배치, 형태, 색채 또는 건축선에 관한 계획</li> 
<li>환경관리계획 및 경관 계획</li> 
<li>교통처리계획</li> 
</ul> 
<h2>지구단위계획 구영별 수립지침 및 지침도 등</h2> 
<p class="txt-tip txt-small"><i class="fa fa-fw fa-exclamation-circle"></i>스마트 폰으로 다운로드 시 데이터 손실이 있을 수 있습니다.</p> 
<div class="down_list mt_30"> 
<ul> 
<li><em>대덕수청지구 지구단위계획</em><a title="대덕수청지구 지구단위계획 PDF(다운로드) 새창열림" class="btn btn-ani btn-file" href="/gonet/FileDownload.do?fileName=01.pdf&amp;code=download" target="_blank"><span class="bico bticon left acrobat2"></span>다운로드</a><a title="새창열림" class="btn btn-ani btn-file" href="/synapsoft/FileViewer.do?atchFileId=FILE_000000001033073&amp;fileSn=0" target="_blank"><span class="bico bticon left acrobat2"></span>바로보기</a></li> 
<li><em>대덕수청지구 지구단위계획 지침도</em><a title="대덕수청지구 지구단위계획 지침도 PDF(다운로드) 새창열림" class="btn btn-ani btn-file" href="/gonet/FileDownload.do?fileName=02.pdf&amp;code=download" target="_blank"><span class="bico bticon left acrobat2"></span>다운로드</a><a title="새창열림" class="btn btn-ani btn-file" href="/synapsoft/FileViewer.do?atchFileId=FILE_000000001033073&amp;fileSn=2" target="_blank"><span class="bico bticon left acrobat2"></span>바로보기</a></li> 
<li><em>당진1지구 지구단위계획</em><a title="당진1지구 지구단위계획 PDF(다운로드) 새창열림" class="btn btn-ani btn-file" href="/gonet/FileDownload.do?fileName=03.pdf&amp;code=download" target="_blank"><span class="bico bticon left acrobat2"></span>다운로드</a><a title="새창열림" class="btn btn-ani btn-file" href="/synapsoft/FileViewer.do?atchFileId=FILE_000000001033073&amp;fileSn=3" target="_blank"><span class="bico bticon left acrobat2"></span>바로보기</a></li> 
<li><em>당진1지구 지구단위계획 지침도</em><a title="당진1지구 지구단위계획 지침도 PDF(다운로드) 새창열림" class="btn btn-ani btn-file" href="/gonet/FileDownload.do?fileName=04.pdf&amp;code=download" target="_blank"><span class="bico bticon left acrobat2"></span>다운로드</a><a title="새창열림" class="btn btn-ani btn-file" href="/synapsoft/FileViewer.do?atchFileId=FILE_000000001033073&amp;fileSn=4" target="_blank"><span class="bico bticon left acrobat2"></span>바로보기</a></li> 
<li><em>송산2일반산업단지 지구단위계획</em><a title="송산2일반산업단지 지구단위계획 PDF(다운로드) 새창열림" class="btn btn-ani btn-file" href="/gonet/FileDownload.do?fileName=05.pdf&amp;code=download" target="_blank"><span class="bico bticon left acrobat2"></span>다운로드</a><a title="새창열림" class="btn btn-ani btn-file" href="/synapsoft/FileViewer.do?atchFileId=FILE_000000001033073&amp;fileSn=5" target="_blank"><span class="bico bticon left acrobat2"></span>바로보기</a></li> 
<li><em>송산2일반산업단지 지침도</em><a title="송산2일반산업단지 지침도 PDF(다운로드) 새창열림" class="btn btn-ani btn-file" href="/gonet/FileDownload.do?fileName=06.pdf&amp;code=download" target="_blank"><span class="bico bticon left acrobat2"></span>다운로드</a><a title="새창열림" class="btn btn-ani btn-file" href="/synapsoft/FileViewer.do?atchFileId=FILE_000000001033073&amp;fileSn=6" target="_blank"><span class="bico bticon left acrobat2"></span>바로보기</a></li> 
<li><em>석문국가산업단지 지구단위계획</em><a title="석문국가산업단지 지구단위계획 PDF(다운로드) 새창열림" class="btn btn-ani btn-file" href="/gonet/FileDownload.do?fileName=07.pdf&amp;code=download" target="_blank"><span class="bico bticon left acrobat2"></span>다운로드</a><a title="새창열림" class="btn btn-ani btn-file" href="/synapsoft/FileViewer.do?atchFileId=FILE_000000001033073&amp;fileSn=7" target="_blank"><span class="bico bticon left acrobat2"></span>바로보기</a></li> 
<li><em>석문국가산업단지 지구단위계획 지침도</em><a title="석문국가산업단지 지구단위계획 지침도 PDF(다운로드) 새창열림" class="btn btn-ani btn-file" href="/gonet/FileDownload.do?fileName=08.pdf&amp;code=download" target="_blank"><span class="bico bticon left acrobat2"></span>다운로드</a><a title="새창열림" class="btn btn-ani btn-file" href="/synapsoft/FileViewer.do?atchFileId=FILE_000000001033073&amp;fileSn=8" target="_blank"><span class="bico bticon left acrobat2"></span>바로보기</a></li> 
<li><em>합덕지방일반산업단지 지구단위계획</em><a title="합덕지방일반산업단지 지구단위계획 PDF(다운로드) 새창열림" class="btn btn-ani btn-file" href="/gonet/FileDownload.do?fileName=09.pdf&amp;code=download" target="_blank"><span class="bico bticon left acrobat2"></span>다운로드</a><a title="새창열림" class="btn btn-ani btn-file" href="/synapsoft/FileViewer.do?atchFileId=FILE_000000001033073&amp;fileSn=9" target="_blank"><span class="bico bticon left acrobat2"></span>바로보기</a></li> 
<li><em>합덕지방일반산업단지 지구단위계획 지침도</em><a title="합덕지방일반산업단지 지구단위계획 지침도 PDF(다운로드) 새창열림" class="btn btn-ani btn-file" href="/gonet/FileDownload.do?fileName=10.pdf&amp;code=download" target="_blank"><span class="bico bticon left acrobat2"></span>다운로드</a><a title="새창열림" class="btn btn-ani btn-file" href="/synapsoft/FileViewer.do?atchFileId=FILE_000000001033073&amp;fileSn=10" target="_blank"><span class="bico bticon left acrobat2"></span>바로보기</a></li> 
<li><em>합덕인더스파크 지구단위계획</em><a title="합덕인더스파크 지구단위계획 PDF(다운로드) 새창열림" class="btn btn-ani btn-file" href="/gonet/FileDownload.do?fileName=11.pdf&amp;code=download" target="_blank"><span class="bico bticon left acrobat2"></span>다운로드</a><a title="새창열림" class="btn btn-ani btn-file" href="/synapsoft/FileViewer.do?atchFileId=FILE_000000001033074&amp;fileSn=0" target="_blank"><span class="bico bticon left acrobat2"></span>바로보기</a></li> 
<li><em>합덕인더스파크 지구단위계획 지침도</em><a title="합덕인더스파크 지구단위계획 지침도 PDF(다운로드) 새창열림" class="btn btn-ani btn-file" href="/gonet/FileDownload.do?fileName=12.pdf&amp;code=download" target="_blank"><span class="bico bticon left acrobat2"></span>다운로드</a><a title="새창열림" class="btn btn-ani btn-file" href="/synapsoft/FileViewer.do?atchFileId=FILE_000000001033074&amp;fileSn=1" target="_blank"><span class="bico bticon left acrobat2"></span>바로보기</a></li> 
<li><em>우강송산지구 지구단위계획</em><a title="우강송산지구 지구단위계획 PDF(다운로드) 새창열림" class="btn btn-ani btn-file" href="/gonet/FileDownload.do?fileName=13.pdf&amp;code=download" target="_blank"><span class="bico bticon left acrobat2"></span>다운로드</a><a title="새창열림" class="btn btn-ani btn-file" href="/synapsoft/FileViewer.do?atchFileId=FILE_000000001033074&amp;fileSn=2" target="_blank"><span class="bico bticon left acrobat2"></span>바로보기</a></li> 
<li><em>우강송산지구 지구단위계획 지침도</em><a title="우강송산지구 지구단위계획 지침도 PDF(다운로드) 새창열림" class="btn btn-ani btn-file" href="/gonet/FileDownload.do?fileName=14.pdf&amp;code=download" target="_blank"><span class="bico bticon left acrobat2"></span>다운로드</a><a title="새창열림" class="btn btn-ani btn-file" href="/synapsoft/FileViewer.do?atchFileId=FILE_000000001033074&amp;fileSn=3" target="_blank"><span class="bico bticon left acrobat2"></span>바로보기</a></li> 
<li><em>남산지구 주거형 지구단위계획 시행지침 및 지침도</em><a title="남산지구 주거형 지구단위계획 시행지침 및 지침도 PDF(다운로드) 새창열림" class="btn btn-ani btn-file" href="/gonet/FileDownload.do?fileName=15.pdf&amp;code=download" target="_blank"><span class="bico bticon left acrobat2"></span>다운로드</a><a title="새창열림" class="btn btn-ani btn-file" href="/synapsoft/FileViewer.do?atchFileId=FILE_000000001033074&amp;fileSn=4" target="_blank"><span class="bico bticon left acrobat2"></span>바로보기</a></li> 
<li><em>용두리지구 주거형 지구단위계획 시행지침 및 지침도</em><a title="용두리지구 주거형 지구단위계획 시행지침 및 지침도 PDF(다운로드) 새창열림" class="btn btn-ani btn-file" href="/gonet/FileDownload.do?fileName=16.pdf&amp;code=download" target="_blank"><span class="bico bticon left acrobat2"></span>다운로드</a><a title="새창열림" class="btn btn-ani btn-file" href="/synapsoft/FileViewer.do?atchFileId=FILE_000000001033074&amp;fileSn=5" target="_blank"><span class="bico bticon left acrobat2"></span>바로보기</a></li> 
<li><em>주거형 지구단위계획(덕마리,봉소리,상거리,한진리) 시행지침 및 지침도</em><a title="주거형 지구단위계획(덕마리,봉소리,상거리,한진리) 시행지침 및 지침도 PDF(다운로드) 새창열림" class="btn btn-ani btn-file" href="/gonet/FileDownload.do?fileName=17.pdf&amp;code=download" target="_blank"><span class="bico bticon left acrobat2"></span>다운로드</a><a title="새창열림" class="btn btn-ani btn-file" href="/synapsoft/FileViewer.do?atchFileId=FILE_000000001033074&amp;fileSn=6" target="_blank"><span class="bico bticon left acrobat2"></span>바로보기</a></li> 
<li><em>당진 송악지구 도시개발사업 지구단위계획 시행지침 및 지침도</em><a title="당진 송악지구 도시개발사업 지구단위계획 시행지침 및 지침도 PDF(다운로드) 새창열림" class="btn btn-ani btn-file" href="/gonet/FileDownload.do?fileName=18.pdf&amp;code=download" target="_blank"><span class="bico bticon left acrobat2"></span>다운로드</a><a title="새창열림" class="btn btn-ani btn-file" href="/synapsoft/FileViewer.do?atchFileId=FILE_000000001033074&amp;fileSn=7" target="_blank"><span class="bico bticon left acrobat2"></span>바로보기</a></li> 
<li><em>통정리지구 주거형 지구단위계획 시행지침 및 지침도(당진시 고시 제2018-307호)</em><a title="통정리지구 주거형 지구단위계획 시행지침 및 지침도(당진시 고시 제2018-307호)PDF(다운로드) 새창열림" class="btn btn-ani btn-file" href="/gonet/FileDownload.do?fileName=2018-307.pdf&amp;code=download" target="_blank"><span class="bico bticon left acrobat2"></span>다운로드</a><a title="새창열림" class="btn btn-ani btn-file" href="/synapsoft/FileViewer.do?atchFileId=FILE_000000001033074&amp;fileSn=8" target="_blank"><span class="bico bticon left acrobat2"></span>바로보기</a></li> 
</ul></div>
